version: '3'

services:
  redis1:
    image: redis:7.2.4
    container_name: redis1
    restart: always
    ports:
      - "6379:6379"
      - "16379:16379"
    volumes:
      - /docker/redis/cluster/redis1/data:/data
      - ./config/redis1.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    networks:
      - redis_network

  redis2:
    image: redis:7.2.4
    container_name: redis2
    restart: always
    ports:
      - "6380:6379"
      - "16380:16379"
    volumes:
      - /docker/redis/cluster/redis2/data:/data
      - ./config/redis2.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    networks:
      - redis_network

  redis3:
    image: redis:7.2.4
    container_name: redis3
    restart: always
    ports:
      - "6381:6379"
      - "16381:16379"
    volumes:
      - /docker/redis/cluster/redis3/data:/data
      - ./config/redis3.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    networks:
      - redis_network

networks:
  redis_network:
    driver: bridge 