services:
  redis:
    image: redis:7.2.4
    container_name: redis-standalone
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /docker/redis/standalone/data:/data
      - /docker/redis/standalone/logs:/var/log/redis
      - ./config/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    networks:
      - redis_network

networks:
  redis_network:
    driver: bridge 